Recargas
jonathanlevrero/NubiProyecto pull request #1
Opened 2020-03-19 17:15 UTC by MatiiAutalan

#Resumen. 

Cree la sección de Recargas.
Tengo una duda de como quedan el fondo en relacion a como esta en los templates pero no pude hacer que queden exactamente iguales. 
Centre los titulos, textos y botones por que entendia que quedaba mejor visualmente que alineado a la izquierda.

2020-03-20 18:19 UTC, jmtov requested changes
¡Muy bieeeen! 🎉 

Como comentario general te diría que, si puedes, uses los nombres de las clases en inglés. Si no, no problemo. Solo intenta mantener los nombres de las clases simples para facilitar la legibilidad.

Te dejé un par de comments para que revises, porfa.

2020-03-20 18:19 UTC, jmtov commented on nubilanding/src/components/recargas/recargas.js
> +                        <img className={styles.logosF} src= {LogoTripAdvisor} alt="Logo Trip Advisor"/>
La clase `logosF` es muy similar a la clase de `logos`, quizá usando un [pseudo selector](https://www.w3schools.com/cssref/sel_last-child.asp) para seleccionar el último elemento de una lista con el mismo className podrías evitar crear una clase adicional.

También te recomendaría que, como la clase es para un sólo logo, la clase se llame `logo` y no `logos`, ya que semánticamente sería más correcta.

2020-03-20 18:19 UTC, jmtov commented on nubilanding/src/components/recargas/styles.module.scss
> +@import url('https://fonts.googleapis.com/css?family=Roboto:400,500|Rubik:400,500&display=swap');
Te diría que cargaras esta fuente en el archivo de estilos generales de la aplicación para que se pueda usar en todos los componentes y no solo acá.

2020-03-20 18:19 UTC, jmtov commented on nubilanding/src/components/recargas/recargas.js
> +                    <div className={styles.contenedorLogosSF}>
Acá también podrías hacer uso de los [pseudo selectores](https://www.w3schools.com/cssref/sel_last-child.asp) para seleccionar el segundo elemento con la misma clase. Así no tienes que crear ninguna clase adicional y es más fácil entender el código desde el CSS.

2020-03-20 18:49 UTC, MMarussi commented on nubilanding/src/components/recargas/styles.module.scss
> +    border-right: solid 2px #d8d8d8;
Es preferible crear variables para usar colores como por ejemplo:
`$azul: #d8d8d8` (no sé si es azul jaja)

Así da una mejor idea de que color se está usando y si por alguna casualidad te piden cambiar todo lo que sea de un color a otro solo modificas esa variable

2020-03-20 18:49 UTC, MMarussi commented on nubilanding/src/components/recargas/styles.module.scss
> +    border-right: solid 2px #d8d8d8;
De paso crearía un archivo **variables.scss** que tenga las variables de los colores que vayan necesitando a medida que desarrollan la aplicación. Para usar esos colores tienen que importar ese archivo en el .scss que quieran usar los colores

2020-03-21 14:44 UTC, MatiiAutalan commented on nubilanding/src/components/recargas/styles.module.scss
>      border-right: solid 2px #d8d8d8;
En este caso solo es el color de borde para que se separen cada uno de los logos. Pero lo voy a tener en cuenta para los demas colores, de titulos, botones, etc .
Gracias por la sugerencia

2020-03-21 14:46 UTC, MatiiAutalan reviewed
Tome las sugerencias y use pseudo selectores para los logos que llevaban una clase diferente y le cambie el nombre a la clase de los logos.

2020-03-27 14:18 UTC, jmtov requested changes

2020-03-27 14:18 UTC, jmtov commented on nubilanding/src/components/recargas/recargas.js
> +                        <img  src= {LogoTripAdvisor} alt="Logo Trip Advisor"/>
¿Estas seguro que al quitar la clase `logo` te sigue funcionando?

Asegúrate que el pseudo selector esté usando la clase como debe ser:

```suggestion
                        <img className={styles.logo} src={LogoTripAdvisor} alt="Logo Trip Advisor"/>
```

Después en el SCSS para seleccionar el último elemento que tenga la clase `.logo` harías algo como:
`.logo:last-child { ... }`

Más sobre [:last-child](https://www.w3schools.com/cssref/sel_last-child.asp)

2020-03-27 14:18 UTC, jmtov commented on nubilanding/src/components/recargas/recargas.js
> +                    <div className={styles.contenedorLogosSF}>
Para lo contenedores (tanto para el que es actualmente `contenedorLogosPF` y `contenedorLogosSF`) puedes usar la misma clase de contenedor:
```suggestion
                    <div className={styles.contenedorLogos}>
```

Luego en el SCSS seleccionarías el último usando nuevamente el `:last-child`:
```
.contenedorLogos:last-child { ... }
```

2020-03-27 17:26 UTC, MatiiAutalan reviewed
Corregi el error de quirarle la clase .logo a las ultimas imagenes, y aplique la recomendación de usar pseudo selectores para los contenedores de logos. Ademas corregi los espacios de mas que habia en el codigo

2020-03-27 18:01 UTC, jmtov approved these changes
¡Hermoso ese código!

2020-03-30 13:49 UTC, merged