Blog
jonathanlevrero/NubiProyecto pull request #10
Opened 2020-04-02 14:33 UTC by jenn-lang

Maquetado de la sección blog la parte visual, mi duda es si dejo centrado el contenido o del lado izquierdo.
antes
![Captura de pantalla de 2020-03-31 20-07-00](https://user-images.githubusercontent.com/57498273/78261176-4902d580-74d5-11ea-94e0-30fe1818817d.png)
ahora
![Captura de pantalla de 2020-04-02 11-11-30](https://user-images.githubusercontent.com/57498273/78261221-58821e80-74d5-11ea-8514-89de96b728c6.png)

2020-04-02 15:23 UTC, jenn-lang commented
Arregle la imagen y acomode las propiedades
![Captura de pantalla de 2020-04-02 12-13-10](https://user-images.githubusercontent.com/57498273/78266811-a6e6eb80-74dc-11ea-8bbb-70236292d642.png)

2020-04-02 16:04 UTC, MatiiAutalan requested changes

2020-04-02 16:04 UTC, MatiiAutalan commented on nubilanding/src/components/blog/blog.js
> +}
Revisar la identacion del codigo! Al final habiamos hablado que ibamos a usar una identacion de 2, pero ahi estas usando una de mas de 2.

2020-04-03 02:30 UTC, MatiiAutalan approved these changes

2020-04-03 14:31 UTC, MMarussi requested changes
Buen trabajo! Dale que ya casi lo tenés!

2020-04-03 14:31 UTC, MMarussi commented on nubilanding/src/App.js
> +    <Blog />
No te olvides del pobre identado(?
```suggestion
      <Blog />
```

2020-04-03 14:31 UTC, MMarussi commented on nubilanding/src/components/blog/blog.js
> +      <div className={styles.contenedorGeneral}>
Este componente puede ser definido como función en lugar que de clase ya que no usa state ni ningún método de cliclo de vida, así no se cargan métodos que no se van a usar en el componente.
```suggestion
function Blog() {
  return (
    <div className={styles.contenedorGeneral}>
```

2020-04-03 14:31 UTC, MMarussi commented on nubilanding/src/components/blog/blog.js
> +export default Blog;
Cuidado que a este archivo le falta la línea vacía al final

2020-04-03 14:31 UTC, MMarussi commented on nubilanding/src/components/blog/form.js
> +  }
El state está definido 2 veces :thinking:
```suggestion
  state = { email: '' };
```

2020-04-03 14:31 UTC, MMarussi commented on nubilanding/src/components/blog/form.js
> +      [e.target.email]: e.target.value
```suggestion
      email: e.target.value
```

2020-04-03 14:31 UTC, MMarussi commented on nubilanding/src/components/blog/form.js
> +          onChange={this.onChange.bind(this)}
Esto viene de la mano con lo del state duplicado:

Al declarar el state con constructor es necesario hacer los bindings de las funciones ya que las mismas no saben que es "this", pero hay una forma en la que se realizan automáticamente.

Para eso tenés que declarar tus funciones como arrow functions (**=>**) así no necesitas hacer un bind del "this" sino que infiera el this de su contexto de ejecución. Acá tenés una [explicación más detallada](https://medium.com/@nikolalsvk/loosing-bind-this-in-react-8637ebf372cf)

```JSX
class Form extends React.Component {
  state = { email: ' ' }

  onChange = event => this.setState({ email: e.target.value })

  render() {
  ...
  onChange={this.onChange}
```

2020-04-03 14:31 UTC, MMarussi commented on nubilanding/src/components/blog/form.js
> +export default Form;
Ojo que este archivo no tiene una línea vacía al final

2020-04-03 14:31 UTC, MMarussi commented on nubilanding/src/components/blog/styles.module.scss
> +  margin-left: -45px; /* para que el btn este sobre el input*/
Es preferible no usar márgenes, paddings, ni ningún atributo de espaciado con números negativos, ya que es un tanto antinatural distanciar cosas con números negativos. Fijate de hacer lo mismo con `position: relative` (ya lo tenés) y algún cambio en la posición

2020-04-03 14:31 UTC, MMarussi commented on nubilanding/src/components/blog/styles.module.scss
> +  margin-top: -30px;
Mismo, fijate si usando `position: relative` podés conseguir el mismo resultado

2020-04-03 14:39 UTC, jmtov requested changes
¡Muy buen trabajo, Jenny! 💪 

Te dejé un par de comentarios, quizá se repitan algunos con los de Tincho.

2020-04-03 14:39 UTC, jmtov commented on nubilanding/src/App.js
> +    <Blog />
Ten cuidado con la indentación:
```suggestion
      <Blog />
```

2020-04-03 14:39 UTC, jmtov commented on nubilanding/src/components/blog/blog.js
> +          <p className={styles.textoDos}>suscribiendote a nuestro Blog</p>
¿Para qué la clase de `textoDos`? Si necesitas seleccionar el último elemento podrías usar una [pseudo clase](https://www.w3schools.com/css/css_pseudo_classes.asp).

2020-04-03 14:39 UTC, jmtov commented on nubilanding/src/components/blog/blog.js
> +          <botton className={styles.ver}>Ver blog</botton>
¿`botton` o `button`?

2020-04-03 14:39 UTC, jmtov commented on nubilanding/src/components/blog/blog.js
> +export default Blog;
Recuerda la línea vacía al final de los archivos.

2020-04-03 14:39 UTC, jmtov commented on nubilanding/src/components/blog/form.js
> +  }
No es necesario este constructor ya que estás inicializando el estado en la línea de arriba.

2020-04-03 14:39 UTC, jmtov commented on nubilanding/src/components/blog/form.js
> +  render() {
Presta atención a los espaciados entre los métodos para facilitar la legibilidad.
```suggestion
  }

  render() {
```

2020-04-03 14:39 UTC, jmtov commented on nubilanding/src/components/blog/form.js
> +        <botton type="submit" name="boton" className={styles.enviar}></botton>
1. Puedes usar la notación `<elemento />` para elementos que no tienen contenido.
2. No es necesario o que hagas `this.onChange.bind(this)` ya que por defecto en componentes de clase, React pasa en los eventos la información de this.
3. El nombre del atributo `name` en el botón podría ser más descriptivo para que refleje más la acción del botón y su rol dentro del formulario. `boton-enviar` podría ser mejor.
```suggestion
        <input
          type="email"
          name="email"
          placeholder="Dejanos tu email"
          value={this.state.email}
          onChange={this.onChange}
          className={styles.input}  />
        <button type="submit" name="boton" className={styles.enviar} />
```

2020-04-03 14:39 UTC, jmtov commented on nubilanding/src/components/blog/form.js
> +export default Form;
Recuerda la línea vacía al final del archivo.

2020-04-03 14:39 UTC, jmtov commented on nubilanding/src/components/blog/styles.module.scss
> +  margin: -30px 0px;
Normalmente puedes acomodar el contenido manipulando el padding del padre o las márgenes del elemento anterior. Con eso evitas el uso de márgenes negativas.

2020-04-03 14:39 UTC, jmtov commented on nubilanding/src/components/blog/styles.module.scss
> +}
Recuerda los comentarios sobre el uso de pseudo-clases y sobre el uso de las márgenes negativas.

2020-04-03 14:39 UTC, jmtov commented on nubilanding/src/components/blog/styles.module.scss
> +  background-color: #d9d9d9;
Te recomiendo empezar a usar variables para los colores de la aplicación pues hace más fácil que los colores sean estándar para todxs quienes trabajan en la app.

2020-04-03 14:39 UTC, jmtov commented on nubilanding/src/components/blog/styles.module.scss
> +  margin-left: -45px; /* para que el btn este sobre el input*/
Cuidado con el uso de las márgenes negativas acá también.

2020-04-03 14:39 UTC, jmtov commented on nubilanding/src/components/blog/styles.module.scss
> +  border: transparent solid 5px;
¿Es necesario un borde transparente de 5px?

2020-04-03 14:39 UTC, jmtov commented on nubilanding/src/components/blog/styles.module.scss
> +  border: transparent solid 5px;
También acá.

2020-04-03 14:39 UTC, jmtov commented on nubilanding/src/components/blog/styles.module.scss
> +  border: transparent solid 5px;
Y acá.

2020-04-06 16:09 UTC, jenn-lang commented
Gracias, ya hice los arreglos y quedo así
![Captura de pantalla de 2020-04-06 12-48-37](https://user-images.githubusercontent.com/57498273/78579736-c39a6080-7807-11ea-9305-a849ee22cbca.png)

2020-04-06 18:32 UTC, briangerez requested changes
Excelente trabajo! 🎉 Te dejo dos comentarios simples y me sumo a la recomendación que hizo @jmtov sobre el uso de variables en los estilos 😄

2020-04-06 18:32 UTC, briangerez commented on nubilanding/src/App.css
> -.App {
Si no se va a usar este archivo, podes eliminarlo directamente

2020-04-06 18:32 UTC, briangerez commented on nubilanding/src/components/blog/blog.js
> +        <p className={styles.texto}>suscribiendote a nuestro Blog</p>
Aquí suscribiéndote lleva tilde

2020-04-06 18:34 UTC, briangerez commented
Y también tenes conflictos de merge para resolver 😄

2020-04-08 18:34 UTC, jenn-lang commented on nubilanding/src/components/blog/styles.module.scss
> +  background-color: #d9d9d9;
Ok, después de juntar todas las ramas de vista principal haremos las variables.

2020-04-09 14:05 UTC, briangerez approved these changes
Dos comentarios muy tranquilos! Fijense de mejorarlo en próximos PRs! Excelente trabajo!

2020-04-09 14:05 UTC, briangerez commented on nubilanding/src/App.js
>      <div className="App">
Creo que no tiene la className "App". Para el próximo podes eliminar este div y dejar solo el Blog

2020-04-09 14:05 UTC, briangerez commented on nubilanding/src/components/blog/styles.module.scss
> +  height: 470px; /*ajuste el matamaño del contenedor a la de la imagen*/
matamaño 👀

2020-04-10 21:26 UTC, merged