Header
jonathanlevrero/NubiProyecto pull request #11
Opened 2020-04-02 18:17 UTC by jonathanlevrero

2020-04-03 01:44 UTC, MatiiAutalan requested changes

2020-04-03 01:44 UTC, MatiiAutalan commented on nubilanding/src/components/Header/Header.js
> +
Este espacio se podria quitar.

2020-04-03 01:44 UTC, MatiiAutalan commented on nubilanding/src/App.js
> +import Header from './components/Header/Header'
falta un espacio entre los import y la funcion.

2020-04-03 01:44 UTC, MatiiAutalan commented on nubilanding/src/components/Header/Header.js
> +
```suggestion
```
igual que estos

2020-04-03 01:44 UTC, MatiiAutalan commented on nubilanding/src/components/Header/Header.js
> +
y estos espacios tambien!

2020-04-03 01:44 UTC, MatiiAutalan commented on nubilanding/src/components/Header/styles.module.scss
> +.Iniciarsesion{
fijarte los espacios cuando termina y empieza una clase de estilos, y fijarte que estamos usando notacion camelCase. Iria de la siguiente forma en este caso: 
```suggestion
.iniciarSesion{
```
La primer palabra siempre en minuscula y las cada ves que empieza una nueva con mayuscula

2020-04-07 17:59 UTC, briangerez commented
Jony! Te sugiero que agregues en la descripción del PR:
Una breve descripción de lo que desarrollaste. 
También podes agregar el link de la card de Trello.
Imagen de invision o la que utilizaste como diseño.
Imagen de cómo quedó lo que desarrollaste.

Esto nos ayuda poder hacer un mejor seguimiento de lo que desarrollaste. También ayuda a ver si pudiste seguir el diseño! 😄

2020-04-07 19:21 UTC, MatiiAutalan approved these changes
Buenisimo!

2020-04-07 20:56 UTC, briangerez requested changes

2020-04-07 20:56 UTC, briangerez commented on nubilanding/src/App.js
> +import Header from './components/Header/Header'
El nombre del archivo del Header, debería comenzar con minúscula (header.js). Para mantener el mismo formato de nombre de archivos en todo el proyecto. 😄

2020-04-07 20:56 UTC, briangerez commented on nubilanding/src/App.css
>    text-align: center;
Es necesario este estilo para envolver al `<Header />` ? 
Si es así, puede ponerlo directamente dentro de los estilos del componente y quitarlo de acá

2020-04-07 20:56 UTC, briangerez commented on nubilanding/src/components/Header/styles.module.scss
> +@import url("https://fonts.googleapis.com/css?family=Roboto:400,500|Rubik:300,400,500&display=swap");
El import lo podes definir dentro del **nubilanding/src/index.scss** para que sea global para todo el proyecto 😄

2020-04-07 20:56 UTC, briangerez commented on nubilanding/src/components/Header/styles.module.scss
> +$color-fondo: #eeeeee;
Luego los colores los podes definir dentro de una carpeta ubicada en nubilanding/src/scss/colors.scss con, por ejemplo:

`$color-boton: #567efb;`

y luego importarlos dentro del styles.module.scss y usarlas:
@import '../../scss/colors.scss';

¡Excelente el querer usar variables! El nombre puede ser algo más específico, por ejemplo, el nombre del color.

2020-04-10 18:03 UTC, jenn-lang reviewed
Buen trabajo, te dejo algunas sugerencias

2020-04-10 18:03 UTC, jenn-lang commented on nubilanding/src/App.js
> +import header from "./components/Header/header";
Tendrías que cambiar de aca '/Header/Header' los nombres de estos carpeta-archivo esten todo minuscula
y dejar en mayuscula los otros(import Header, <Header /> -por que sino no te los lee y no se ve en la web)

2020-04-10 18:03 UTC, jenn-lang commented on nubilanding/src/components/Header/header.js
> +export default header;
Aquí como en export y el nombre la función deberían estar en mayúscula header como antes tenias;

2020-04-10 18:03 UTC, jenn-lang commented on nubilanding/src/index.scss
>  body {
Aquí poner un espacio de linea entre estas dos

2020-04-10 18:14 UTC, jenn-lang commented
En estilos arreglar la consistencia de espacios de  las clases con la llaves y que entre las clases  estén separadas por una linea vacía;
En la clase nav ul  le quites la linea de mas- lo mismo en export de header.js

2020-04-11 11:56 UTC, jonathanlevrero commented on nubilanding/src/components/Header/styles.module.scss
> +$color-fondo: #eeeeee;
Pensabamos corregir esto cuando tengamos todo integrado en una sola vista para que sea más sencillo

2020-04-13 19:58 UTC, jmtov requested changes
¡Buen trabajo, Jonni!  Te dejé un par de comentarios.

2020-04-13 19:58 UTC, jmtov commented on nubilanding/src/App.js
> +    <Header/>
Ten en cuenta la indentación.
```suggestion
      <Header/>
```

2020-04-13 19:58 UTC, jmtov commented on nubilanding/src/components/header/header.js
> +    </header>);
Y acá también:
```suggestion
    return (
      <header>
        <nav>
          <ul>
            <button className={styles.registrate}>Registrate Gratis</button>
            <button className={styles.iniciarSesion}>Iniciar Sesión</button>
            <button className={styles.navicon}> &#9776; </button>
          </ul>
        </nav>
      </header>
    );
```

2020-04-13 19:58 UTC, jmtov commented on nubilanding/src/components/header/styles.module.scss
> +
No dejes espacios de más.

2020-04-13 19:58 UTC, jmtov commented on nubilanding/src/components/header/styles.module.scss
> +.registrate{
Espacio entre textos y símbolos:
```suggestion
.registrate {
```

2020-04-13 19:58 UTC, jmtov commented on nubilanding/src/components/header/styles.module.scss
> +.iniciarSesion{
Igual acá: 
```suggestion
.iniciarSesion {
```

2020-04-13 19:58 UTC, jmtov commented on nubilanding/src/components/header/styles.module.scss
> +.navicon{
Y acá: 
```suggestion
.navicon {
```

2020-04-14 06:02 UTC, merged