Privacidad
jonathanlevrero/NubiProyecto pull request #13
Opened 2020-04-06 20:07 UTC by MatiiAutalan

#Resumen.
Realicé el maquetado de la sección de privacidad.
Una ves aprovado hay que incorporarle el footer y el header para que esté completa.
![privacidad](https://user-images.githubusercontent.com/57498145/78600064-9e6a1a00-7828-11ea-930f-512c2cac8526.gif)

2020-04-08 14:17 UTC, briangerez requested changes

2020-04-08 14:17 UTC, briangerez commented on nubilanding/src/components/privacidad/privacidad.js
> +export default Privacidad;
Agregar un enter al final del archivo!

2020-04-08 14:17 UTC, briangerez commented on nubilanding/src/components/privacidad/privacidad.js
> +        <h1>Política de privacidad Nubi</h1>
Podrías poner los estilos directamente sobre el tag h1, para no agregar un div de más

2020-04-08 14:17 UTC, briangerez commented on nubilanding/src/components/privacidad/privacidad.js
> +      <div className={styles.contenedorTituloSecundario}>
Acá también

2020-04-08 14:17 UTC, briangerez commented on nubilanding/src/components/privacidad/styles.module.scss
> +  font-family: "Roboto";
Veo que usan este fuente en varias partes, les recomiendo que lo agregen al index.scss como para que ya esté seteada para toda la página y sólo especifiquen el font en casos que no sea la "Roboto". Repito, es una recomendación no más 😃

2020-04-08 14:23 UTC, briangerez commented on nubilanding/src/components/privacidad/styles.module.scss
> +.contenedorInformacion {
Quizás dentro de esta clase, puedes poner los tags h2 y el p como para no repetir el código de `className={styles.tituloSeccion}` y `className={styles.texto}`

2020-04-08 14:23 UTC, briangerez commented
Matu, excelente laburo! Agregué unos comentarios y sugerencias. Cualquier cosa me consultan! 🎉

2020-04-08 17:46 UTC, MatiiAutalan commented
Agregue el espacio al final del archivo, al tag h2 "subtitulo" le quite los div y le di estilos directamente, agrupe clases con tags para evitar repetir las clases de estilos en el archivo privacidad.js.
Al tag h1 no le aplique directamente los estilos ya que el contenedorTituloPrincipal me sirve para posicionar la imagen de fondo.

2020-04-09 14:14 UTC, briangerez approved these changes

2020-04-09 14:15 UTC, briangerez commented
Perfecto Matu! Seguí así 💪

2020-04-09 22:56 UTC, merged