Seccion de retiros terminada
jonathanlevrero/NubiProyecto pull request #3
Opened 2020-03-19 18:49 UTC by MatiiAutalan

#Resumen 

Cree seccion de Retiros. 
Tengo una duda de como quedan el fondo en relacion a como esta en los templates pero no pude hacer que queden exactamente iguales.
Centre los titulos, textos, tabla y botones por que entendia que quedaba mejor visualmente que alineado a la izquierda.

2020-03-20 18:26 UTC, jmtov requested changes
¡Súper! 🌟 

Te recomiendo que cuando subas un PR adjuntes un screenshot de lo que hiciste en la descripción del mismo. Con eso quien revisa el PR puede darse una idea de lo que encontrará cuando revise tu trabajo.

Te dejé un par de comentarios para que tengas en cuenta.

2020-03-20 18:26 UTC, jmtov commented on nubilanding/src/components/retiros/retiros.js
> +import styles from '../retiros/styles.module.scss'
Están en la misma carpeta, así que podrías simplemente escribir:
```suggestion
import styles from './styles.module.scss';
```

2020-03-20 18:26 UTC, jmtov commented on nubilanding/src/components/retiros/styles.module.scss
> +.tabla ,td ,th{
Prestar atención a los espacios hace que el código se vea más prolijo:
```suggestion
.tabla ,td ,th {
```

2020-03-24 16:49 UTC, MMarussi commented on nubilanding/src/components/retiros/retiros.js
> +                    </p>
Me parece mejor encarar esto con 2 `<p>` distintos y darle los estilos necesarios para que se vea como querés. Ya que esa separación que generan los `<br/>` tiene significado semántico desde el html (un espacio en blanco) que no tiene mucho sentido, para mi es preferible encararlo desde los estilos y lo visual.

2020-03-24 16:49 UTC, MMarussi commented on nubilanding/src/components/retiros/retiros.js
> +class Retiros extends React.Component {
Podrías definir este componente como una función en lugar de una clase? Al no tener estado y tampoco requerir un manejo especifico de su ciclo de vida se estarían cargando métodos al componente que el mismo nunca va a usar

2020-03-24 20:10 UTC, MatiiAutalan commented
Cambie de Clase a Función y modifique el texto de la tabla sacando los br y poniondolos dentro de una p.

2020-03-24 20:12 UTC, MatiiAutalan reviewed
Cambie de Clase a Funcíon y modifique el texto de la tabla sacando los br y Poniendolos detro de una etiqueta p .

2020-03-27 14:11 UTC, MMarussi approved these changes
Buen trabajo! :ok_hand:

2020-03-27 16:05 UTC, MMarussi commented on nubilanding/src/App.js
> +import Retiros from './components/retiros/retiros'
Agregale un ; al final para que sea consistente con el resto del código

2020-03-27 16:05 UTC, MMarussi commented on nubilanding/src/components/retiros/retiros.js
> +
Esta línea línea en blanco no es necesaria, podrías sacarla?

2020-03-27 16:05 UTC, MMarussi commented on nubilanding/src/components/retiros/retiros.js
> +
Lo mismo con esta

2020-03-30 15:01 UTC, merged