Beneficios
jonathanlevrero/NubiProyecto pull request #5
Opened 2020-03-21 01:01 UTC by jenn-lang

Resumen: agregue estilos modelo de caja y tipografía , y en js modifique el orden de los contenedores; lo que me falto es acomodar  el botón pero no se en qué  no esta funcionando que el fondo sea mas largo para que alcance al botón.

2020-03-21 14:57 UTC, MatiiAutalan requested changes
Hay algunas lineas en el archivo de estilos en las que hay espacios de mas, y hace que se vea medio desordenado el codigo.

2020-03-24 18:20 UTC, MMarussi commented on nubilanding/src/components/beneficios/beneficios.js
> +class Beneficios extends React.Component{
Podrías definir este componente como una función en lugar de una clase?
Al no tener estado y tampoco requerir un manejo especifico de su ciclo de vida se estarían cargando métodos al componente que el mismo nunca va a usar.

2020-03-24 18:53 UTC, jenn-lang commented
Gracias,listo seguí las sugerencias ( ordenar los espacios - cambiar la clase por una función) y ya puede arreglar el fondo.

2020-03-24 19:28 UTC, MatiiAutalan approved these changes
Genial!

2020-03-27 17:50 UTC, jenn-lang commented
Listo ya arregle la falta de consistencia que era borrar los espacios que estaban de mas y cambiar los nombres  iguales de los contenedores.

2020-03-27 19:09 UTC, MMarussi commented on nubilanding/src/components/beneficios/beneficios.js
> +            <div className= {styles.contenedorGeneral}>
Cuidado que a partir de está línea se está identando con 4 espacios de más
```suggestion
        <div className= {styles.contenedorGeneral}>
```

2020-03-27 19:09 UTC, MMarussi commented on nubilanding/src/components/beneficios/beneficios.js
> +
Esta línea en blanco se puede borrar :smile:

2020-03-27 20:48 UTC, MMarussi commented on nubilanding/src/components/beneficios/beneficios.js
> +                        <br></br> Sin comisiones ocultas.</p>
Esta línea quedo medio rara, podés chequear la identación de la misma.
Igualmente te recomiendo que en lugar de un `<p>` con un `<br>` dentro uses 2 `<p>` y les asignes estilos para llegar al mismo resultado. Ya que el html se encarga del "qué" se va a mostrar y el css del "como" y si bien el `<br>` funciona la separación entre elementos es un cuestión más visual (cómo).

2020-04-01 02:48 UTC, jenn-lang commented
tambien hice otros cambiaos como agrandar  el top y bottom  porque revise el  templete y me pareció mas grande y quiere  saber si esta bien.

![Captura de pantalla de 2020-03-31 23-24-52](https://user-images.githubusercontent.com/57498273/78094081-0abcc780-73aa-11ea-9b33-a3416a3e84e3.png)

2020-04-01 02:49 UTC, jenn-lang commented
asi lo tenia antes 
![Captura de pantalla de 2020-03-30 14-19-11](https://user-images.githubusercontent.com/57498273/78094171-4a83af00-73aa-11ea-8cc9-6c03574653f6.png)

2020-04-01 02:52 UTC, jenn-lang commented
asi quedo con los cambios nuevos
![Captura de pantalla de 2020-03-31 23-25-10](https://user-images.githubusercontent.com/57498273/78094324-a3ebde00-73aa-11ea-826e-b93ab79d0cbc.png)
![Captura de pantalla de 2020-03-31 23-24-52](https://user-images.githubusercontent.com/57498273/78094327-a5b5a180-73aa-11ea-86bf-546f786d2d90.png)

2020-04-01 02:57 UTC, jenn-lang commented
en la primera me equivoque, queria poner como estaba en el templete  que es esta
![Captura de pantalla de 2020-03-31 23-44-09](https://user-images.githubusercontent.com/57498273/78094567-368c7d00-73ab-11ea-81b4-a13f277bfcb7.png)

2020-04-01 03:06 UTC, jenn-lang commented
recién ahora le hice esos cambios de agrandar el top y bottom porque antes no me salio, y luego que pude agrandar el fondo  se paso que era mas grande esos espacios, mi duda es si están bien esas medidas o lo dejo como antes?

2020-04-01 18:35 UTC, MatiiAutalan commented on nubilanding/src/components/beneficios/styles.module.scss
> +  height: 50px;
Creo que no haria falta ponerle un height para esta parte por que te limitas a despues tener qe usar una position: absolute con el boton despues que no es necesario. Si le sacas esa propiedad el boton se va a acomodar abajo del contenedor de beneficios.

2020-04-01 18:36 UTC, MatiiAutalan commented on nubilanding/src/components/beneficios/styles.module.scss
> +  position: absolute;
Como te digo arriba no haria falta usar absolute , ni acomodarlo tanto al boton ya que sacandole el heigth se va a posicionar abajo del contenedo.

2020-04-01 18:38 UTC, MatiiAutalan commented on nubilanding/src/components/beneficios/styles.module.scss
> +  margin: 50px 50px 30px 25px;
Quisas quedaria mejor que tengan un margen todos parejos, ir probando hasta que te qeden bien acomodados. Por ejemplo margin : 40 px.
```suggestion
  margin: 40px;
```

2020-04-01 18:47 UTC, MatiiAutalan commented on nubilanding/src/components/beneficios/styles.module.scss
> +  color: #faf3fd;
tambien le agregaria un width, para agrandar un poquito el largo del boton.

2020-04-01 19:03 UTC, MatiiAutalan submitted a review, later dismissed
Ahi te deje una sugerencia para revisar

2020-04-01 19:36 UTC, MMarussi commented on nubilanding/src/components/beneficios/styles.module.scss
> +.texto, .textoUltimo {
Sólo una sugerencia, no es necesario que lo cambies.
Tené en cuenta que SASS te permite usar la siguiente sintaxis

```
.texto {
  .textoUltimo {
    font-family: "Roboto";
    font-weight: 400;
    font-size: 18px;
    color: #5e737e;
  }
}
```

2020-04-01 20:27 UTC, MMarussi approved these changes
Buen trabajo!

2020-04-01 22:17 UTC, jenn-lang commented
gracias por las sugerencias, ya hice los cambios y quedo mejor porque arreglo algo que antes no me había dado cuenta (centrar el contenedor).

2020-04-02 19:16 UTC, merged