Registrarse
jonathanlevrero/NubiProyecto pull request #6
Opened 2020-03-21 14:58 UTC by MatiiAutalan

2020-03-27 14:19 UTC, MMarussi commented on nubilanding/src/components/registrarse/registrarse.js
> +class Registrarse extends React.Component {
Este componente de clase sin estado ni manejo definido de ciclo de vida puede definirse como función así no se cargan métodos que no se van a usar y podemos sacar el render() dle código y queda más limpio!

2020-03-27 14:57 UTC, MMarussi commented
Fijate que github marca los archivos a los que le falta de línea final con el siguiente símbolo:

![Screenshot from 2020-03-27 11-32-37](https://user-images.githubusercontent.com/11763032/77766652-b4086400-701e-11ea-9ca1-f1ef81b5cf4e.png)

En el documento de [estandarización de código](https://docs.google.com/document/d/1gJ0gB1NkinQXyRe5dk71yMUYE8c6dupLc-lYQ0osSro) están indicados los pasos para que VScode lo haga automáticamente por vos al guardar los cambios del archivo! (qué trucazo no?).
Además de eso por las duda chequeen con el equipo el documento de nuevo ya que actualizamos algunas cosas y agregamos una sección que habla sobre la identación del código.

2020-03-27 18:08 UTC, MatiiAutalan reviewed
Cambie que sea clase por una funcion y acomode los espacios de mas en el codigo.

2020-03-30 17:28 UTC, MMarussi requested changes
Solo unos detalles, ya casi lo tenés cocinado! :+1:

2020-03-30 17:28 UTC, MMarussi commented on nubilanding/src/components/registrarse/registrarse.js
> +import styles from "../registrarse/styles.module.scss";
Podés no es necesario ir al directorio padre para encontrar el archivo de estilos, como están en la misma carpeta podés referenciarlo así:
```suggestion
import styles from "./styles.module.scss";
```

2020-03-30 17:28 UTC, MMarussi commented on nubilanding/src/components/registrarse/styles.module.scss
> +  width: 17%;
Para el ancho de botones es preferible que se use un número fijo y no porcentajes, ya que para pantallas más chicas ese 17% puede terminar siendo muy chico (podés hacer la prueba usando el inspector de elementos y presionar Ctrl + Shift + M para ver como se comporta tu sitio con una pantalla más chica).
Por lo general se usan 100% para ocupar todo el espacio posible dentro del padre que contiene al elemento en cuestión y por ejemplo 50% cuando tenemos 2 elementos en una misma línea.

2020-03-30 17:28 UTC, MMarussi commented on nubilanding/src/components/registrarse/styles.module.scss
> +  width: 17%;
Esto también aplica también para el margin y el padding.

Una de las cosas que podés hacer si querés tener en mente un diseño responsive es usar [mediaqueries](https://www.w3schools.com/cssref/css3_pr_mediaquery.asp) en tu scss

2020-03-30 18:52 UTC, jonathanlevrero approved these changes

2020-04-01 04:05 UTC, jenn-lang approved these changes

2020-04-01 19:24 UTC, MMarussi approved these changes
Bien ahí!

Fijate que tenés conflictos que resolver :grimacing:

2020-04-01 20:40 UTC, merged