Footer
jonathanlevrero/NubiProyecto pull request #7
Opened 2020-03-26 16:01 UTC by MatiiAutalan

#Resumen.

Seccion de footer terminada.
![Screenshot from 2020-03-26 12-57-37](https://user-images.githubusercontent.com/57498145/77668218-e3a56680-6f61-11ea-9519-e7822e62e3ac.png)

2020-03-30 18:57 UTC, jonathanlevrero approved these changes

2020-04-01 05:18 UTC, jenn-lang commented
Esta genial, solo le faltan algunas correcciones como en el  footer.js linea 42 tiene un ; de mas, en styles poner las comillas por igual, poner en una  font-weight y para que quede mas lindo el codigo seria bueno que mantengas el mismo orden con las propiedades  que se repiten en los distintos contenedores (repetir el orden de las propiedades que tengan similitud, estén juntas -lo relacionado con display) como hiciste con los logos.

2020-04-01 13:43 UTC, jenn-lang commented on nubilanding/src/components/footer/styles.module.scss
> +.contenedorLogoNubi {
```suggestion
.contenedorLogoNubi {
```
poner todo junto lo que tenga que ver con posicionar al elemento-clase

2020-04-01 14:29 UTC, MatiiAutalan commented
Dejo como se ve la funcionalidad de los logos de las redes
![Peek 2020-03-31 16-56](https://user-images.githubusercontent.com/57498145/78149097-fa3d3900-740b-11ea-8cb0-cfb446009864.gif)

2020-04-01 14:43 UTC, jenn-lang approved these changes

2020-04-01 14:43 UTC, jenn-lang commented on nubilanding/src/components/footer/styles.module.scss
> +}
que display este arriba de flex-direction

2020-04-01 14:43 UTC, jenn-lang commented on nubilanding/src/components/footer/styles.module.scss
> +}
poner text-align arriba de widht

2020-04-01 14:43 UTC, jenn-lang commented on nubilanding/src/components/footer/styles.module.scss
> +}
y tambien este para que compares y veas  si vas a seguir este orden  porque en otra clase el text-align lo tenes diferente la linea 14

2020-04-01 15:03 UTC, MatiiAutalan commented on nubilanding/src/components/footer/styles.module.scss
> +}
Y este ahi lo modifique. Gracias por las correcciones!

2020-04-01 20:24 UTC, MMarussi requested changes

2020-04-01 20:24 UTC, MMarussi commented on nubilanding/src/App.css
> +@import url('https://fonts.googleapis.com/css?family=Roboto:400,500|Rubik:400,500&display=swap');
Fijate que falta la línea vacía al final

2020-04-01 20:24 UTC, MMarussi commented on nubilanding/src/components/footer/styles.module.scss
> +.contenedorLogoNubi p {
Sólo una sugerencia, podés cambiarlo si te gusta o no.

Podés aprovechar la sintaxis que ofrece SASS para este caso que sería:
```SCSS
.contenedorLogoNubi {
  p {
    font-family: "Roboto";
    text-align: center;
    margin-top: -5px;
    font-size: 11px;
    color: #979696;
  }
}
```

2020-04-01 20:24 UTC, MMarussi commented on nubilanding/src/components/footer/footer.js
> +          <button><img src={LogoInstagram} alt="Logo Instagram" /></button>
Probaste usar sólo la imagen sin wrappearla con un botón o mismo que sea sólo un botón con una imagen de background? Eso reduciría los elementos de html y mismo te puede ayudar a unificar varías de las clases de sass en 1/2 clases

2020-04-01 20:24 UTC, MMarussi commented on nubilanding/src/components/footer/styles.module.scss
> +.logosRedes button:nth-child(1) img:hover {
Que te parece crear clases descriptivas como .logoInstagram, .logoTwitter y así para cada logo en vez de usar :nth-child()? Así cada elemento en el JSX tiene asociado su estilo y uno puede saber mejor que estilo corresponde a que logo

Además de eso todas estas clases tienen el mismo `border-radius` y el mismo `margin` que el botón sin hover

2020-04-01 20:24 UTC, MMarussi commented on nubilanding/src/components/footer/styles.module.scss
> +}
Para mejorar la sugerencia: acá tenemos uno de los mejores ejemplos para usar el anidamiento de clases de SASS

Abajo de esta clase tenemos las clases `.contenedorBotones button` y `.contenedorBotones button:hover`.
Que sería nada más agregarle un hover a esta clase, eso mismo se puede implementar de la siguiente manera:

```SCSS
.contenedorBotones {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  justify-content: space-evenly;
  align-items: flex-end;
  width: 37%;
  margin-top: 65px;

  button {
    background-color: #4a494a;
    border: 5px solid #4a494a;
    border-radius: 30px;
    text-align: center;
    color: #ffffff;
    width: 29%;
    height: 25px;
    margin: 0 0 20px 0;
    font-size: 10px;

    &:hover {
      background-color: grey;
      border: solid grey;
    }
  }
}
```

2020-04-02 16:16 UTC, MMarussi approved these changes
Buenísimo! :muscle:

2020-04-02 16:16 UTC, MMarussi commented on nubilanding/src/components/footer/styles.module.scss
> +    margin-top: -5px;
En lo posible intenta no usar valores negativos en los mágenes ni en el padding porque marcan espacio entre elementos y es antinatural que algo este a -20px de distancia de otra cosa. Talvez con un `position: relative` un posicionando el elemento podés hacer lo mismo.

2020-04-02 16:16 UTC, MMarussi commented on nubilanding/src/components/footer/styles.module.scss
> +  border: 7px solid #bc2a8d;
Acá sólo estas cambiando el color del borde así que con un `border-color:` debería ser suficiente

2020-04-02 19:54 UTC, merged