Home
jonathanlevrero/NubiProyecto pull request #8
Opened 2020-03-26 17:35 UTC by jonathanlevrero

Sección Home terminada, se agregó un último commit de corrección de un botón

2020-03-30 13:47 UTC, MatiiAutalan requested changes

2020-03-30 13:47 UTC, MatiiAutalan commented on nubilanding/src/components/home/home.js
Creo que quedaron espacios de más, en esta linea y en la 28, 30 y 31 que estan de mas y queda raro el codigo.

2020-03-30 18:47 UTC, MatiiAutalan approved these changes

2020-03-30 19:29 UTC, merged

2020-03-30 20:01 UTC, MMarussi reviewed
Tengan cuidado que se agregó un archivo `nubilanding/src/assets/PressKitNubi-20170622T162123Z-001.zip` que pesa como 13 MB (bastante) y al ser un .zip no creo que lo estén usando, también un `nubilanding/src/assets/vendor/_keep` asi que por mi pueden sacarlos del repo.

2020-03-30 20:01 UTC, MMarussi commented on nubilanding/src/App.js
> +import Home from './components/home/home';
Fijate que tienen imports con " " y otros con ' ', no sé que habrán decidido cómo equipo pero intenten mantener la consistencia

2020-03-30 20:14 UTC, MMarussi reviewed
En otros PRs usaron camelCase para las clases de scss (tienen código en development así también), para mantener la consistencia estaría bueno que todas las clases estén en camelCase, mismo porque hace un poco más legibles las clases cuyo nombre son más de 1 palabra.
Por ejemplo:
```
// En vez de usar
.botonflex {
  ...
}

// Usar
.botonFlex {
  ...
}
```

2020-03-30 20:14 UTC, MMarussi commented on nubilanding/src/components/home/home.js
> +          <div className={styles.nubipaypal}>
Puede ser que no necesites este div porque estás aplicando casi todas las propiedades de `nubipresentacion`, lo unico distinto es el padding que se lo podés aplicar a la imagen

2020-03-30 20:14 UTC, MMarussi commented on nubilanding/src/components/home/home.js
> +          <div className={styles.titulo}>
Es un caso parecido a `nubipresentacion`

2020-03-30 20:48 UTC, MMarussi commented on nubilanding/src/components/home/styles.module.scss
> +
Este espacio vacío se puede borrar

2020-03-30 20:48 UTC, MMarussi commented on nubilanding/src/components/home/styles.module.scss
> +  flex-direction: row;
`flex-direction: row` es el valor por defecto cuando aplicas `display: flex` asi que no es necesario especificarlo a menos que estés sobreescribiendo una clase :smile:

2020-03-30 20:48 UTC, MMarussi commented on nubilanding/src/components/home/styles.module.scss
> +  flex-wrap: nowrap;
Mismo que `flex-direction: row` este es el default de flex-wrap

2020-03-30 20:48 UTC, MMarussi commented on nubilanding/src/components/home/styles.module.scss
> +  padding-bottom: 3%;
Para estos casos es preferible usar un número fijo (5px por ejemplo). Hay tener en cuenta que si la pantalla es muy angosta (el % depende del ancho del elemento padre y por ende del tamaño de la pantalla en gran parte) el padding puede resultar siendo menor de lo que querés o en otro caso mayor.
En la mayoría de los casos no hay un porcentaje que cubra los distintos anchos de pantallas.

2020-03-30 20:48 UTC, MMarussi commented on nubilanding/src/components/home/styles.module.scss
> +
Este espacio en blanco se puede borrar

2020-04-01 13:44 UTC, MMarussi commented on nubilanding/src/components/home/styles.module.scss
> +  margin-bottom: -20px;
Intentaría evitar los márgenes y paddings negativos, siendo sincero intentaría evitar lo más que pueda los valores negativos más que nada porque es un poco antinatural el manejo de estos (no digo que esté mal, sólo que los usaría lo mínimo indispensable). Preferiría encararlo usando `position: relative`