Calculadora
jonathanlevrero/NubiProyecto pull request #9
Opened 2020-03-31 20:34 UTC by MatiiAutalan

#Resumen.

Cree la seccion de la calculadora, solo la parte del maquetado.
![Screenshot from 2020-03-31 17-31-21](https://user-images.githubusercontent.com/57498145/78072525-a849d400-7375-11ea-8832-d9303ef98ebe.png)

2020-04-02 21:56 UTC, MMarussi requested changes
Viene bienn!

Que te parece crear y usar clases de scss en lugar de usar selectores de html? Eso te va a permitir que en caso de que a lo largo de la aplicación se use mucho un estilo que puedas reutilizarlo por medio de la clase, además de que evitamos posibles problemas de especificidad y provee cierto estándar.

2020-04-02 21:56 UTC, MMarussi commented on nubilanding/src/components/calculadora/calculadora.js
> +        <div>
Es necesario este div?

2020-04-02 21:56 UTC, MMarussi commented on nubilanding/src/components/calculadora/calculadora.js
> +            </label>
Revisa la identación acá y recordá que los elementos vacíos se pueden cerrar en el primer tag:

```suggestion
            <label className={styles.inputRadio} htmlFor="recarga">
              RECARGA
              <input type="radio" id="recarga" name="tipodeoperacion" value="recarga"/>
              <span className={styles.marcado} />
            </label>
```

2020-04-02 21:56 UTC, MMarussi commented on nubilanding/src/components/calculadora/calculadora.js
> +            </label>
Igual que anterior

2020-04-02 21:56 UTC, MMarussi commented on nubilanding/src/components/calculadora/calculadora.js
> +            </label>
Revisar identación también

2020-04-02 21:56 UTC, MMarussi commented on nubilanding/src/components/calculadora/styles.module.scss
> +label {
Es preferible que crees y uses una clase en lugar de utilizar selectores de html

2020-04-02 21:56 UTC, MMarussi commented on nubilanding/src/components/calculadora/styles.module.scss
> +}
Usando la sintaxis de sass podés tener 1 clase sola con los selectores anidados

2020-04-02 21:56 UTC, MMarussi commented on nubilanding/src/components/calculadora/styles.module.scss
> +.inputRadio:hover input ~ .marcado {
Esta combinacion de selectores se pueden definir dentro de `.inputRadio` y sin tener que usar el sibling combinator(~) por lo que te podés sacar el selector `input` de encima con la ayuda de la sintaxis de sass,

```SCSS
.inputRadio {
  display: block;
  position: relative;
  padding-left: 35px;
  margin-bottom: 12px;
  cursor: pointer;
  font-size: 18px;

  &:hover {
    .marcado {
        background-color: #ccc;
    }
  }
}
```

2020-04-02 21:56 UTC, MMarussi commented on nubilanding/src/components/calculadora/styles.module.scss
> +}
Usando la sintaxis de sass podés tener 1 clase sola con los pseudo-selectores anidados

2020-04-03 00:59 UTC, MatiiAutalan commented
Ya resolvi las correcciones! Gracias.

2020-04-03 15:47 UTC, MMarussi commented on nubilanding/src/components/calculadora/styles.module.scss
> +  input {
Crea una clase para aplicar estos estilos

2020-04-03 15:47 UTC, MMarussi commented on nubilanding/src/components/calculadora/styles.module.scss
> +.inputRadio input:checked ~ .marcado {
Acá podrías hacer algo parecido a lo que hiciste con `.inputRadio`

2020-04-05 01:55 UTC, MatiiAutalan commented
Arregle los cambios sugeridos con anterioridad, y ademas cambios sugeridos por el cliente con respecto al input que solo se pueda ingresar numeros dentro de ese campo y que se le de aspecto de inhabilitado a los input radio de recargas y dolares.

2020-04-06 14:30 UTC, briangerez commented
Matu! Hay conflictos que resolver 😄

2020-04-06 14:56 UTC, MMarussi commented on nubilanding/src/components/calculadora/calculadora.js
> +  }
Agrega un espacio acá para tener separado el **onChange** del **render()**

2020-04-06 16:30 UTC, MatiiAutalan commented
> Matu! Hay conflictos que resolver

Sii, con Martin quedamos en que hasta qe no este aprovado el PR , no resolviamos los conflictos por que ya nos paso que se nos escapo una rama que no estaba  aprovada y la mergeamos sin querer! Entonces para evitar eso primero esperamos la aprovacion del PR!

2020-04-06 17:45 UTC, MMarussi approved these changes
Buen trabajo! :ok_hand:

2020-04-06 19:47 UTC, merged